services:
  react-mui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped
    container_name: react-mui-app
    environment:
      - NODE_ENV=production
